require: rubocop-rails

Rails/FilePath:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false
